MOUSEKEY_ENABLE     = yes     # Mouse keys
RGBLIGHT_ENABLE     = no     # Enable WS2812 RGB underlight.
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812
VIA_ENABLE          = yes     # Enable VIA
VIAL_ENABLE         = yes     # Enable VIAL
# VIALRGB_ENABLE = yes
VIAL_INSECURE = yes
KEY_OVERRIDE_ENABLE = no
OLED_ENABLE         = no
OLED_DRIVER         = SSD1306
EXTRAKEY_ENABLE     = yes
LTO_ENABLE          = yes
QMK_SETTINGS        = no
COMBO_ENABLE        = no
ENCODER_ENABLE		= yes
VIAL_ENCODERS_ENABLE = yes
